" Dan George
"{{{Auto Commands
autocmd BufNewFile,BufRead *.py set ft=python
" This seemed slick, but I'm making too many changes and it is annoying
"autocmd BufWritePost $MYVIMRC ++nested source $MYVIMRC
" Remove any trailing whitespace that is in the file
autocmd BufRead,BufWrite * if ! &bin | silent! %s/\s\+$//ge | endif
" Open git commit message in insert mode
autocmd BufRead COMMIT_EDITMSG start
" Define a notes type for model notes
" This doesn't work and I don't know why
"autocmd BufNewFile,BufRead *-notes.txt setf notes
"augroup Notes
  "au!
  "autocmd FileType notes setl nonumber
  "autocmd FileType notes setl norelativenumber
  "autocmd FileType notes setl textwidth=80
  "autocmd FileType notes setl wrapmargin=8
"augroup END
"{{{Source files
augroup Source
  au!
"{{{Define templates
" Need to change these so that alternate buf isn't the template file
  autocmd BufNewFile *.sh 0r ~/.vim/templates/bash.tpl | normal G
  " Too often accidentally open a new source file by typo
  "autocmd BufNewFile *.c,*.h,*.cc,*.cpp,*.hpp 0r ~/.vim/templates/C_copyright.tpl | normal G
"}}}
"{{{Base
  autocmd FileType c,cpp,python setl nu
  autocmd FileType c,cpp,python setl rnu
  autocmd FileType c,cpp,python setl colorcolumn=100
  autocmd FileType c,cpp setl foldmethod=syntax
  autocmd FileType python setl foldmethod=indent
  autocmd FileType cmake,make,sh setl nu
  autocmd FileType cmake,make,sh setl rnu
  autocmd FileType cmake,make,sh setl colorcolumn=80
"}}}
augroup SourceTabs
  " Need to be able to overide these in project .vimrc files
  au!
"{{{C, C++, and Python
  autocmd FileType c,cpp setl expandtab
  autocmd FileType c,cpp setl tabstop=4
  autocmd FileType c,cpp setl shiftwidth=4
  autocmd FileType c,cpp setl softtabstop=4
  autocmd FileType python setl expandtab
  autocmd FileType python setl tabstop=4
  autocmd FileType python setl shiftwidth=4
  autocmd FileType python setl softtabstop=4
"}}}
"{{{Build files and shell scripts
  autocmd FileType make          setl noexpandtab
  autocmd FileType make          setl tabstop=8
  autocmd FileType make          setl shiftwidth=8
  autocmd FileType cmake,sh      setl softtabstop=8
  autocmd FileType cmake,sh      setl expandtab
  autocmd FileType cmake,sh      setl tabstop=4
  autocmd FileType cmake,sh      setl shiftwidth=4
  autocmd FileType cmake,sh      setl softtabstop=4
"}}}
augroup END
"}}}
"{{{Restore cursor position to where it was before
augroup JumpCursorOnEdit
au!
autocmd BufReadPost *
\ if expand("<afile>:p:h") !=? $TEMP |
\ if line("'\"") > 1 && line("'\"") <= line("$") |
\ let JumpCursorOnEdit_foo = line("'\"") |
\ let b:doopenfold = 1 |
\ if (foldlevel(JumpCursorOnEdit_foo) > foldlevel(JumpCursorOnEdit_foo - 1)) |
\ let JumpCursorOnEdit_foo = JumpCursorOnEdit_foo - 1 |
\ let b:doopenfold = 2 |
\ endif |
\ exe JumpCursorOnEdit_foo |
\ endif |
\ endif
" Need to postpone using "zv" until after reading the modelines.
autocmd BufWinEnter *
\ if exists("b:doopenfold") |
\ exe "normal zv" |
\ if(b:doopenfold > 1) |
\ exe "+".1 |
\ endif |
\ unlet b:doopenfold |
\ endif
augroup END"}}}
"}}}
"{{{Misc Settings
set nocompatible " necesary for lots of cool vim things
set undofile
set ruler
set number
set rnu
set ignorecase
set smartcase
set autoindent          " on new lines, match indent of previous line
set copyindent          " copy the previous indentation on autoindenting
set cindent             " smart indenting for c-like code
set cinoptions=l1,b1,g0,E-s,N-s,t0,(0,W4  " see :h cinoptions-values
set cinkeys+=0=break
set noexpandtab
set smarttab            " smart tab handling for indenting
set magic               " change the way backslashes are used in search patterns
set bs=indent,eol,start " Allow backspacing over everything in insert mode
set nobackup            " no backup~ files.
set autoread
set lazyredraw
let g:is_posix = 1
set tags=./tags;/
set noerrorbells visualbell t_vb=
set exrc

" gdb inside vim
let g:termdebug_popup = 0
let g:termdebug_wide = 163

set showcmd " shows what you are typing as a command

syntax enable " needed for Syntax Highlighting and stuff

filetype on
filetype plugin on
set grepprg=grep\ -nH\ $*

" Use english for spellchecking, but don't spellcheck by default
if version >= 700
set spl=en spell
set nospell
endif

" Cool tab completion stuff
set wildmenu
set wildmode=list:longest,full

" Enable mouse support in console
set mouse+=a

" Let me do things with the mouse inside tmux
if &term =~ '^screen'
    " tmux knows the extended mouse mode
    set ttymouse=xterm2
endif

" Got backspace?
set backspace=2

" Incremental searching is sexy
set incsearch

" Highlight things that we find with the search
set hlsearch
" easily get rid of the highlight, until next search
noremap ./ :nohl<CR>

" Highlight the cursor line
set cursorline

" Help balance brackets
set showmatch

" When I close a tab, remove the buffer from the buffer list
set nohidden

" Set off the other paren
highlight MatchParen ctermbg=4

filetype plugin indent on
filetype indent on
syntax on

"Open new split panes to right and bottom, which feels more natural than
"Vim’s default:
set splitbelow
set splitright
" }}}
"{{{ Functions
"{{{ Open URL in browser

function! Browser ()
let line = getline (".")
let line = matchstr (line, "http[^ ]*")
exec "!firefox ".line
endfunction

"}}}
"{{{Theme Rotating
let themeindex=0
function! RotateColorTheme()
let y = -1
while y == -1
let colorstring = "inkpot#ron#blue#elflord#evening#koehler#murphy#pablo#desert#torte#"
let x = match( colorstring, "#", g:themeindex )
let y = match( colorstring, "#", x + 1 )
let g:themeindex = x + 1
if y == -1
let g:themeindex = 0
else
let themestring = strpart(colorstring, x + 1, y - x - 1)
return ":colorscheme ".themestring
endif
endwhile
endfunction
" }}}
"{{{ Paste Toggle
let paste_mode = 0 " 0 = normal, 1 = paste

func! Paste_on_off()
if g:paste_mode == 0
set paste
let g:paste_mode = 1
else
set nopaste
let g:paste_mode = 0
endif
return
endfunc
"}}}
"}}}
"{{{ Mappings

let mapleader=" "

" Open Url on this line with the browser \w
map <Leader>w :call Browser ()<CR>

" Open the Project Plugin <F2>
nnoremap <silent> <F2> :Project<CR>

" Open the Project Plugin
nnoremap <silent> <Leader>pal :Project .vimproject<CR>

" TODO Mode
nnoremap <silent> <Leader>todo :execute TodoListMode()<CR>

" Open the TagList Plugin <F3>
nnoremap <silent> <F3> :Tlist<CR>

" Next Tab
nnoremap <silent> <C-Right> :tabnext<CR>

" Previous Tab
nnoremap <silent> <C-Left> :tabprevious<CR>

" New Tab
nnoremap <silent> <C-t> :tabnew<CR>

" Rotate Color Scheme <F8>
" nnoremap <silent> <F8> :execute RotateColorTheme()<CR>

" DOS is for fools.
nnoremap <silent> <F9> :%s/$//g<CR>:%s// /g<CR>

" Paste Mode! Dang! <F8>
nnoremap <silent> <F8> :call Paste_on_off()<CR>
set pastetoggle=<F8>

" Edit vimrc \ev
nnoremap <silent> <Leader>ev :tabnew<CR>:e $MYVIMRC<CR>

" Edit gvimrc \gv
nnoremap <silent> <Leader>gv :tabnew<CR>:e ~/.gvimrc<CR>

" Source vimrc
noremap <Leader>sv :source $MYVIMRC<CR>

" Edit bashrc
noremap <Leader>eb :tabnew<CR>:e ~/.bashrc<CR>

" Up and down are more logical with g..
nnoremap <silent> k gk
nnoremap <silent> j gj
inoremap <silent> <Up> <Esc>gka
inoremap <silent> <Down> <Esc>gja

" Good call Benjie (r for i)
nnoremap <silent> <Home> i <Esc>r
nnoremap <silent> <End> a <Esc>r

" Create Blank Newlines and stay in Normal mode
nnoremap <silent> zj o<Esc>
nnoremap <silent> zk O<Esc>

" Space will toggle folds!
nnoremap <space> za

nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
" Search mappings: These will make it so that going to the next one in a
" search will center on the line it's found in.
"map N Nzz
"map n nzz

" Testing
set completeopt=longest,menuone,popup

inoremap <expr> <cr> pumvisible() ? "\<c-y>" : "\<c-g>u\<cr>"
inoremap <expr> <c-n> pumvisible() ? "\<lt>c-n>" : "\<lt>c-n>\<lt>c-r>=pumvisible() ? \"\\<lt>down>\" : \"\"\<lt>cr>"
inoremap <expr> <m-;> pumvisible() ? "\<lt>c-n>" : "\<lt>c-x>\<lt>c-o>\<lt>c-n>\<lt>c-p>\<lt>c-r>=pumvisible() ? \"\\<lt>down>\" : \"\"\<lt>cr>"

" Fix email paragraphs
nnoremap <leader>par :%s/^>$//<CR>

"}}}
"{{{Plugins
"set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
"
" " The following are examples of different formats supported.
" " Keep Plugin commands between vundle#begin/end.
" " plugin on GitHub repo
Plugin 'tpope/vim-fugitive'

" version control gutter (works with git)
Plugin 'airblade/vim-gitgutter'

" Seamlessly navigate between tmux and vim panes
Plugin 'christoomey/vim-tmux-navigator'

" Python Linter
Plugin 'nvie/vim-flake8'
" Edit gpg encrypted files
Plugin 'jamessan/vim-gnupg'

" status bar that rocks
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

Plugin 'editorconfig/editorconfig-vim'
Plugin 'vim-syntastic/syntastic'
Plugin 'ycm-core/YouCompleteMe'
Plugin 'dense-analysis/ale'
Plugin 'tpope/vim-surround'
Plugin 'kien/rainbow_parentheses.vim'

Plugin 'lifepillar/vim-solarized8'

Plugin 'rhysd/vim-clang-format'
"Plugin 'dpelle/vim-LanguageTool'

call vundle#end() " required
"}}}
"{{{Color
function! Solarized8Overrides() abort
        " Unable to make this work correctly with AirlineTheme solarize
        "highlight airline_b     ctermbg=11  ctermfg=8
endfunction
augroup ColorOverrides
        autocmd!
        autocmd ColorScheme solarized8_high call Solarized8Overrides()
augroup END
" Suggested remedy for wrong colors inside tmux
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
set background=dark
colorscheme solarized8_high
"}}}
"{{{Airline
" solarized8_high uses fg/bg combos that have bad contrast, for me
let g:airline_theme = 'sol'
let g:airline#extensions#whitespace#mixed_indent_algo = 1
let g:airline#extensions#ale#enabled = 1
let g:airline#extensions#ale#error_symbol = 'E:'
let g:airline#extensions#ale#warning_symbol = 'W:'
"}}}
"{{{Fugitive
" Fugitive Conflict Resolution
nnoremap <leader>gd :Gvdiffsplit!<CR>
" "diff obtain [local|upstream]"
" local will have //3 in its name
nnoremap dol :diffget //2<CR>
" upstream will have //3 in its name
nnoremap dou :diffget //3<CR>
"}}}
"{{{Syntastic
" Let ale do it, for now

" Don't use recommended statusline with airline
"set statusline+=%#warningmsg#
"set statusline+=%{SyntasticStatuslineFlag()}
"set statusline+=%*

"let g:airline#extensions#syntastic#enabled = 1
"let airline#extensions#syntastic#error_symbol = 'E:'
"let airline#extensions#syntastic#stl_format_err = '%E{[%fe(#%e)]}'
"let airline#extensions#syntastic#warning_symbol = 'W:'
"let airline#extensions#syntastic#stl_format_warn = '%W{[%fw(#%w)]}'

let g:syntastic_aggregate_errors = 1
let g:syntastic_always_populate_loc_list = 0
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
"let g:syntastic_check_on_wq = 0
let g:syntastic_cmake_checkers = ['cmakelint']
let g:syntastic_cpp_checkers = ['gcc'
      \]
let g:syntastic_c_checkers = ['gcc'
      \]
let g:syntastic_cpp_check_header = 1
"let g:syntastic_c_config_file = '.syntastic_c'
"let g:syntastic_cpp_config_file = '.syntastic_cpp'
"let g:syntastic_mode_map = {
"  \"mode": "active",
"  \"active_filetypes": ['sh'],
"  \"passive_filetypes": ['cmake', 'python']
" \}
"}}}
"{{{Ycm
" Fallback to extra conf if no compile DB
" GoTo mappings
" Declaration
" Definition
" References

" Get mappings
" GetParent
" GetDoc

" Refactor mappings
" FixIt

let g:ycm_show_diagnostics_ui = 0
let g:ycm_open_loclist_on_ycm_diags = 0

"}}}
"{{{Cscope
if has("cscope")
        set csprg=/usr/bin/cscope
        set csto=0
        set cst
        set nocsverb
        " add any database in current directory
        if filereadable("cscope.out")
                cs add cscope.out
                " else add database pointed to by environment
        elseif $CSCOPE_DB != ""
                cs add $CSCOPE_DB
        endif
        set csverb
	nmap <C-_>s :cs find s <C-R>=expand("<cword>")<CR><CR>
	nmap <C-_>g :cs find g <C-R>=expand("<cword>")<CR><CR>
	nmap <C-_>c :cs find c <C-R>=expand("<cword>")<CR><CR>
	nmap <C-_>t :cs find t <C-R>=expand("<cword>")<CR><CR>
	nmap <C-_>e :cs find e <C-R>=expand("<cword>")<CR><CR>
	nmap <C-_>f :cs find f <C-R>=expand("<cfile>")<CR><CR>
	nmap <C-_>i :cs find i ^<C-R>=expand("<cfile>")<CR>$<CR>
	nmap <C-_>d :cs find d <C-R>=expand("<cword>")<CR><CR>
	nmap <C-_>a :cs find a <C-R>=expand("<cword>")<CR><CR>

	" Using 'CTRL-spacebar' then a search type makes the vim window
	" split horizontally, with search result displayed in
	" the new window.

	nmap <C-Space>s :scs find s <C-R>=expand("<cword>")<CR><CR>
	nmap <C-Space>g :scs find g <C-R>=expand("<cword>")<CR><CR>
	nmap <C-Space>c :scs find c <C-R>=expand("<cword>")<CR><CR>
	nmap <C-Space>t :scs find t <C-R>=expand("<cword>")<CR><CR>
	nmap <C-Space>e :scs find e <C-R>=expand("<cword>")<CR><CR>
	nmap <C-Space>f :scs find f <C-R>=expand("<cfile>")<CR><CR>
	nmap <C-Space>i :scs find i ^<C-R>=expand("<cfile>")<CR>$<CR>
	nmap <C-Space>d :scs find d <C-R>=expand("<cword>")<CR><CR>
	nmap <C-Space>a :scs find a <C-R>=expand("<cword>")<CR><CR>

	" Hitting CTRL-space *twice* before the search type does a vertical
	" split instead of a horizontal one

	nmap <C-Space><C-Space>s
		\:vert scs find s <C-R>=expand("<cword>")<CR><CR>
	nmap <C-Space><C-Space>g
		\:vert scs find g <C-R>=expand("<cword>")<CR><CR>
	nmap <C-Space><C-Space>c
		\:vert scs find c <C-R>=expand("<cword>")<CR><CR>
	nmap <C-Space><C-Space>t
		\:vert scs find t <C-R>=expand("<cword>")<CR><CR>
	nmap <C-Space><C-Space>e
		\:vert scs find e <C-R>=expand("<cword>")<CR><CR>
	nmap <C-Space><C-Space>i
		\:vert scs find i ^<C-R>=expand("<cfile>")<CR>$<CR>
	nmap <C-Space><C-Space>d
		\:vert scs find d <C-R>=expand("<cword>")<CR><CR>
	nmap <C-Space><C-Space>a
		\:vert scs find a <C-R>=expand("<cword>")<CR><CR>
endif
"}}}
"{{{Ale
let g:ale_set_loclist = 0
let g:ale_linters_ignore = {
\'yaml': ['speectrum']
\,'cc': ['ccls', 'cquery', 'flawfinder', 'clazy-standalone', 'clang++']
\,'c': ['ccls', 'cquery', 'flawfinder', 'clazy-standalone', 'clang++']
\,'markdown': ['alex','languagetool']
\}
let g:ale_fixers = {
\'cc': ['astyle', 'clangtidy', 'clang-format', 'remove_trailing_lines', 'trim_whitespace', 'uncrustify'],
\'python': ['add_blank_lines_for_python_control_statements', 'autoimport', 'autopep8', 'black', 'isort', 'remove_trailing_lines', 'reorder-python-imports', 'trim_whitespace'],
\'yaml': ['remove_trailing_lines', 'trim_whitespace', 'yamlfix'],
\'make': ['remove_trailing_lines', 'trim_whitespace']
\}
let g:ale_c_astyle_project_options = 'project=.astylerc'
let g:ale_cpp_cpplint_options = '--filter=-build/include_subdir,-build/include_order,-whitespace/tab,-readability/cast,-whitespace/braces'
let g:airline#extensions#ale#enable = 1
let g:ale_cmake_cmakelint_options = '--config=.cmakelintrc'
"}}}
set modelines=1
" vim:foldmethod=marker:foldlevel=0:tw=0:ts=2:sw=2:sts=2:et:
